//! Public process continuity, never a secret or execution attestation.
use std::sync::LazyLock;

static INSTANCE_ID: LazyLock<String> = LazyLock::new(|| uuid::Uuid::new_v4().to_string());

/// Generated by this process, not configuration, headers, or request extensions.
#[derive(Debug, Clone, serde::Serialize, cel::DynamicType)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(rename_all = "camelCase")]
#[dynamic(rename_all = "camelCase")]
pub struct GatewayProcess {
	version: u32,
	instance_id: &'static str,
}

impl Default for GatewayProcess {
	fn default() -> Self {
		Self {
			version: 1,
			instance_id: INSTANCE_ID.as_str(),
		}
	}
}

/// Consume informational snapshots, but restore this process's immutable identity.
pub(crate) fn deserialize_current<'de, D: serde::Deserializer<'de>>(
	deserializer: D,
) -> Result<GatewayProcess, D::Error> {
	<serde::de::IgnoredAny as serde::Deserialize>::deserialize(deserializer)?;
	Ok(GatewayProcess::default())
}
