// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: model_router.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RequestedModel string                 `protobuf:"bytes,2,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	// Version one supports openai_chat only. JSON preserves provider extensions
	// without introducing a second schema for the inference API.
	InputFormat string `protobuf:"bytes,3,opt,name=input_format,json=inputFormat,proto3" json:"input_format,omitempty"`
	RequestJson []byte `protobuf:"bytes,4,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	// Exact configured names; candidates are not an authorization grant.
	Candidates []string `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// Values explicitly supplied by gateway CEL expressions. Client headers are
	// not implicitly copied. Authentication must precede routing.
	Context          map[string]string `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PolicyGeneration string            `protobuf:"bytes,7,opt,name=policy_generation,json=policyGeneration,proto3" json:"policy_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_model_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_model_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RouteRequest) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

func (x *RouteRequest) GetInputFormat() string {
	if x != nil {
		return x.InputFormat
	}
	return ""
}

func (x *RouteRequest) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

func (x *RouteRequest) GetCandidates() []string {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *RouteRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RouteRequest) GetPolicyGeneration() string {
	if x != nil {
		return x.PolicyGeneration
	}
	return ""
}

type RouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must echo RouteRequest.policy_generation, including the empty value.
	PolicyGeneration string `protobuf:"bytes,1,opt,name=policy_generation,json=policyGeneration,proto3" json:"policy_generation,omitempty"`
	// At most 16 entries, 64-byte keys and 256-byte values. No prompt content or
	// secrets. Exposed as metadata.grpc_router.diagnostics, never upstream fields.
	Diagnostics map[string]string `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*RouteResponse_Selection
	//	*RouteResponse_Rejection
	Outcome       isRouteResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_model_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_model_router_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetPolicyGeneration() string {
	if x != nil {
		return x.PolicyGeneration
	}
	return ""
}

func (x *RouteResponse) GetDiagnostics() map[string]string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *RouteResponse) GetOutcome() isRouteResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *RouteResponse) GetSelection() *Selection {
	if x != nil {
		if x, ok := x.Outcome.(*RouteResponse_Selection); ok {
			return x.Selection
		}
	}
	return nil
}

func (x *RouteResponse) GetRejection() *Rejection {
	if x != nil {
		if x, ok := x.Outcome.(*RouteResponse_Rejection); ok {
			return x.Rejection
		}
	}
	return nil
}

type isRouteResponse_Outcome interface {
	isRouteResponse_Outcome()
}

type RouteResponse_Selection struct {
	Selection *Selection `protobuf:"bytes,3,opt,name=selection,proto3,oneof"`
}

type RouteResponse_Rejection struct {
	Rejection *Rejection `protobuf:"bytes,4,opt,name=rejection,proto3,oneof"`
}

func (*RouteResponse_Selection) isRouteResponse_Outcome() {}

func (*RouteResponse_Rejection) isRouteResponse_Outcome() {}

type Selection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An exact member of RouteRequest.candidates, never a URL or virtual model.
	Model         string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_model_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_model_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_model_router_proto_rawDescGZIP(), []int{2}
}

func (x *Selection) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type Rejection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of 400, 403, 409, 413, 422, 429, or 503. An intentional rejection is
	// never replaced by a fallback, even when its HTTP status is 503.
	HttpStatus uint32 `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	// A stable nonempty error identifier, at most 64 ASCII letters/digits/_/-.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Safe client-facing explanation, at most 1024 UTF-8 bytes.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejection) Reset() {
	*x = Rejection{}
	mi := &file_model_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejection) ProtoMessage() {}

func (x *Rejection) ProtoReflect() protoreflect.Message {
	mi := &file_model_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejection.ProtoReflect.Descriptor instead.
func (*Rejection) Descriptor() ([]byte, []int) {
	return file_model_router_proto_rawDescGZIP(), []int{3}
}

func (x *Rejection) GetHttpStatus() uint32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *Rejection) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Rejection) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_model_router_proto protoreflect.FileDescriptor

const file_model_router_proto_rawDesc = "" +
	"\n" +
	"\x12model_router.proto\x12\x1aagentgateway.dev.router.v1\"\xf6\x02\n" +
	"\fRouteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0frequested_model\x18\x02 \x01(\tR\x0erequestedModel\x12!\n" +
	"\finput_format\x18\x03 \x01(\tR\vinputFormat\x12!\n" +
	"\frequest_json\x18\x04 \x01(\fR\vrequestJson\x12\x1e\n" +
	"\n" +
	"candidates\x18\x05 \x03(\tR\n" +
	"candidates\x12O\n" +
	"\acontext\x18\x06 \x03(\v25.agentgateway.dev.router.v1.RouteRequest.ContextEntryR\acontext\x12+\n" +
	"\x11policy_generation\x18\a \x01(\tR\x10policyGeneration\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\rRouteResponse\x12+\n" +
	"\x11policy_generation\x18\x01 \x01(\tR\x10policyGeneration\x12\\\n" +
	"\vdiagnostics\x18\x02 \x03(\v2:.agentgateway.dev.router.v1.RouteResponse.DiagnosticsEntryR\vdiagnostics\x12E\n" +
	"\tselection\x18\x03 \x01(\v2%.agentgateway.dev.router.v1.SelectionH\x00R\tselection\x12E\n" +
	"\trejection\x18\x04 \x01(\v2%.agentgateway.dev.router.v1.RejectionH\x00R\trejection\x1a>\n" +
	"\x10DiagnosticsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\aoutcome\"!\n" +
	"\tSelection\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"Z\n" +
	"\tRejection\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\rR\n" +
	"httpStatus\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2k\n" +
	"\vModelRouter\x12\\\n" +
	"\x05Route\x12(.agentgateway.dev.router.v1.RouteRequest\x1a).agentgateway.dev.router.v1.RouteResponseB.Z,github.com/agentgateway/agentgateway/api;apib\x06proto3"

var (
	file_model_router_proto_rawDescOnce sync.Once
	file_model_router_proto_rawDescData []byte
)

func file_model_router_proto_rawDescGZIP() []byte {
	file_model_router_proto_rawDescOnce.Do(func() {
		file_model_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_router_proto_rawDesc), len(file_model_router_proto_rawDesc)))
	})
	return file_model_router_proto_rawDescData
}

var file_model_router_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_model_router_proto_goTypes = []any{
	(*RouteRequest)(nil),  // 0: agentgateway.dev.router.v1.RouteRequest
	(*RouteResponse)(nil), // 1: agentgateway.dev.router.v1.RouteResponse
	(*Selection)(nil),     // 2: agentgateway.dev.router.v1.Selection
	(*Rejection)(nil),     // 3: agentgateway.dev.router.v1.Rejection
	nil,                   // 4: agentgateway.dev.router.v1.RouteRequest.ContextEntry
	nil,                   // 5: agentgateway.dev.router.v1.RouteResponse.DiagnosticsEntry
}
var file_model_router_proto_depIdxs = []int32{
	4, // 0: agentgateway.dev.router.v1.RouteRequest.context:type_name -> agentgateway.dev.router.v1.RouteRequest.ContextEntry
	5, // 1: agentgateway.dev.router.v1.RouteResponse.diagnostics:type_name -> agentgateway.dev.router.v1.RouteResponse.DiagnosticsEntry
	2, // 2: agentgateway.dev.router.v1.RouteResponse.selection:type_name -> agentgateway.dev.router.v1.Selection
	3, // 3: agentgateway.dev.router.v1.RouteResponse.rejection:type_name -> agentgateway.dev.router.v1.Rejection
	0, // 4: agentgateway.dev.router.v1.ModelRouter.Route:input_type -> agentgateway.dev.router.v1.RouteRequest
	1, // 5: agentgateway.dev.router.v1.ModelRouter.Route:output_type -> agentgateway.dev.router.v1.RouteResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_model_router_proto_init() }
func file_model_router_proto_init() {
	if File_model_router_proto != nil {
		return
	}
	file_model_router_proto_msgTypes[1].OneofWrappers = []any{
		(*RouteResponse_Selection)(nil),
		(*RouteResponse_Rejection)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_router_proto_rawDesc), len(file_model_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_router_proto_goTypes,
		DependencyIndexes: file_model_router_proto_depIdxs,
		MessageInfos:      file_model_router_proto_msgTypes,
	}.Build()
	File_model_router_proto = out.File
	file_model_router_proto_goTypes = nil
	file_model_router_proto_depIdxs = nil
}
