// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: model_router.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelRouter_Route_FullMethodName = "/agentgateway.dev.router.v1.ModelRouter/Route"
)

// ModelRouterClient is the client API for ModelRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Selects a configured model before inference. This service never proxies model
// responses. A routing reservation is not evidence of successful inference.
type ModelRouterClient interface {
	Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
}

type modelRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewModelRouterClient(cc grpc.ClientConnInterface) ModelRouterClient {
	return &modelRouterClient{cc}
}

func (c *modelRouterClient) Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, ModelRouter_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelRouterServer is the server API for ModelRouter service.
// All implementations must embed UnimplementedModelRouterServer
// for forward compatibility.
//
// Selects a configured model before inference. This service never proxies model
// responses. A routing reservation is not evidence of successful inference.
type ModelRouterServer interface {
	Route(context.Context, *RouteRequest) (*RouteResponse, error)
	mustEmbedUnimplementedModelRouterServer()
}

// UnimplementedModelRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelRouterServer struct{}

func (UnimplementedModelRouterServer) Route(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedModelRouterServer) mustEmbedUnimplementedModelRouterServer() {}
func (UnimplementedModelRouterServer) testEmbeddedByValue()                     {}

// UnsafeModelRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelRouterServer will
// result in compilation errors.
type UnsafeModelRouterServer interface {
	mustEmbedUnimplementedModelRouterServer()
}

func RegisterModelRouterServer(s grpc.ServiceRegistrar, srv ModelRouterServer) {
	// If the following call panics, it indicates UnimplementedModelRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelRouter_ServiceDesc, srv)
}

func _ModelRouter_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelRouterServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelRouter_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelRouterServer).Route(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelRouter_ServiceDesc is the grpc.ServiceDesc for ModelRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentgateway.dev.router.v1.ModelRouter",
	HandlerType: (*ModelRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _ModelRouter_Route_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model_router.proto",
}
