// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package api

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RouteRequest
func (this *RouteRequest) MarshalJSON() ([]byte, error) {
	str, err := ModelRouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RouteRequest
func (this *RouteRequest) UnmarshalJSON(b []byte) error {
	return ModelRouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RouteResponse
func (this *RouteResponse) MarshalJSON() ([]byte, error) {
	str, err := ModelRouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RouteResponse
func (this *RouteResponse) UnmarshalJSON(b []byte) error {
	return ModelRouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Selection
func (this *Selection) MarshalJSON() ([]byte, error) {
	str, err := ModelRouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Selection
func (this *Selection) UnmarshalJSON(b []byte) error {
	return ModelRouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Rejection
func (this *Rejection) MarshalJSON() ([]byte, error) {
	str, err := ModelRouterMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Rejection
func (this *Rejection) UnmarshalJSON(b []byte) error {
	return ModelRouterUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ModelRouterMarshaler   = &jsonpb.Marshaler{}
	ModelRouterUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
